I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 17, in script call
    call teachingfirst
  File "game/SceneScript/teaching1.rpy", line 127, in script
    show ale standing s
Exception: Image 'ale standing' does not accept attributes 's'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 17, in script call
    call teachingfirst
  File "game/SceneScript/teaching1.rpy", line 127, in script
    show ale standing s
  File "C:\Users\Jeevan\Desktop\Research of VN\RenPy Game\renpy-8.3.2-sdk\renpy\ast.py", line 1111, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Jeevan\Desktop\Research of VN\RenPy Game\renpy-8.3.2-sdk\renpy\ast.py", line 1074, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Jeevan\Desktop\Research of VN\RenPy Game\renpy-8.3.2-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Jeevan\Desktop\Research of VN\RenPy Game\renpy-8.3.2-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Jeevan\Desktop\Research of VN\RenPy Game\renpy-8.3.2-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Users\Jeevan\Desktop\Research of VN\RenPy Game\renpy-8.3.2-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'ale standing' does not accept attributes 's'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.3.24111502
RealGame 1.0
Thu Nov 21 17:34:54 2024
